---

# dependencies
- name: install redis, nodejs, npm
  yum: name={{ item }} state=present
  with_items:
      - redis
      - nodejs
      - npm
      - git

# redis
#

- name: enable overcommit_memory for redis
  sysctl: name=vm.overcommit_memory value=1 state=present

- name: enable redis server
  service: name=redis enabled=yes state=started

# haste-server
#
# Clones the repo and doesn't pull if it is
# already cloned.
- name: get latest haste-server from GitHub
  git: repo=https://github.com/seejohnrun/haste-server
       dest=/opt/haste-server/
       update=no
  tags: git

# add systemd service
- name: systemd service file present
  copy: src=haste-server.service
        dest=/etc/systemd/system/haste-server.service

# Does 'npm install' only the first time
- name: make sure we have done 'npm install'
  command: npm install
  args:
      chdir: /opt/haste-server
      creates: /opt/haste-server/node_modules

- name: configuration for haste-server
  copy: src=config.js
        dest=/opt/haste-server/config.js
  notify: restart haste-server

- name: allow http (80/tcp) in firewalld
  firewalld: service=http permanent=true state=enabled
  notify: reload firewalld

- name: start and enable haste-server
  service: name=haste-server enabled=yes state=started
