---

- name: install redis, nodejs, npm
  yum: name={{ item }} state=present
  with_items:
      - redis
      - nodejs
      - npm
      - git

- name: enable redis server
  service: name=redis enabled=yes state=started

- name: get latest haste-server from GitHub
  git: repo=https://github.com/seejohnrun/haste-server
       dest=/opt/haste-server/
  tags: git

- name: systemd service file present
  copy: src=haste-server.service
        dest=/etc/systemd/system/haste-server.service
