---

- name: apply base configuration to all nodes
  hosts: all

  roles:
    - base

- name: apply storage server config (iscsi,nfs)
  hosts: storage

  roles:
    - iscsi_target
    - nfs_server

- name: apply iscsi initiator config
  hosts: iscsi_initiators

  roles:
    - iscsi_initiator

- name: configure haste-server
  hosts: haste

  roles:
    - epel
